### ISSUE TITLE
Scenario Outlines to avoid having to cut and paste

### ISSUE THREAD

**Issue by planglue** [elight/coulda#8]
I really like the simplicity of what you have going here.  And I'm about ready to choose coulda over cucumber.

 That said, tt was mentioned somewhere that you were not going to implement fit tables as they could be supported in given clauses.  That may be true, but what about using tables for scenario outlines.  These handy little guys could save a ton of cut and pasting.  Or am I missing a better way to do something?

See related link.
http://wiki.github.com/aslakhellesoy/cucumber/scenario-outlines

**Comment by elight** [comment]
For now, the simplest way to do this is to factor your Scenario into a method (yes, you can do this ;-) ) that accept parameters.

For example, it is perfectly legal to do this:

```
def canned_scenario_with_args(params = {})
  Scenario "My canned senario" do
    Given "A given parameter like #{params[:first_given]}" do
      ....
    end
    When "An event parameter like #{params[:first_when]}" do
      ....
    end
    Then "An expectation parameter like #{params[:first_then]}" do
      ....
    end
  end
end
```

Want to get whackier?  It's perfectly legitimate to pass Procs in Hashes.  So, occasionally, I wrote my Coulda tests but inject even more behavior instead of just data.  The only downside I find is that the backtrace can become a bit difficult to untangle at times.

```
def canned_scenario_with_args(params = {})
  Scenario "My canned senario" do
    Given "A given parameter like #{params[:first_given]}" do
      ...
      eval(params[:first_given])
      ...
    end
    When "An event parameter like #{params[:first_when]}" do
      ...
      eval(params[:first_when])
      ...
    end
    Then "An expectation parameter like #{params[:first_then]}" do
      ...
      eval(params[:first_then])
      ...
    end
  end
end

canned_scenario_with_args(
  :first_given => lambda {
    ...
  },
  :first_when => lambda {
    ...
  },
  :first_then => lambda {
    ...
  }
)
```

To the original point, I'm not averse to using FIT-like tables with Coulda.  However, I am hesitant to introduce them into Coulda directly.  I prefer an ecology of tools that play well together versus a single monolithic tool that tries to be everything to everyone.  I've discussed with a few people, at times, extracting FIT-like table support from Cucumber in such a way that it would be reusable within arbitrary Ruby code including Coulda.

However, adding Scenario Outlines would likely require tighter integration.

**Comment by elight** [comment]
FWIW, I've been using Coulda regularly in my consulting.  I often extract steps (Given, When, etc.) out into methods that are sometimes reusable across Features. And, yes, I do the same thing within a single Feature as well for Scenarios.

Unlike Cucumber, Coulda is just Ruby.  It's important to remember that.  You have access to the full Ruby language instead of a coupling of a Turing incomplete programming language (Gherkin) with Ruby.
